#!/bin/bash
echo "Armbian 'armbian-bsp-cli-rk3128-box-current' for '1-PC8f91-V5e5d-He14c-B8122-Rf36a': 'preinst' starting."
set +e # NO ERROR CONTROL, for compatibility with legacy Armbian scripts.
#set -e # Debugging


## begin contents of 'board_side_bsp_cli_preinst'
    [ "$1" = "upgrade" ] && touch /var/run/.reboot_required;
    sed -i "s/^COMPRESS=.*/COMPRESS=gzip/" /etc/initramfs-tools/initramfs.conf;
    grep -q vm.swappiness /etc/sysctl.conf;
    case $? in 
        0)
            sed -i 's/vm\.swappiness.*/vm.swappiness=100/' /etc/sysctl.conf
        ;;
        *)
            echo vm.swappiness=100 >> /etc/sysctl.conf
        ;;
    esac;
    sysctl -p > /dev/null 2>&1;
    if [ -d "/var/lib/ubuntu-advantage/messages/" ]; then
        echo -e "\nSupport Armbian! \nLearn more at https://armbian.com/donate" > /var/lib/ubuntu-advantage/messages/apt-pre-invoke-esm-service-status;
        cp /var/lib/ubuntu-advantage/messages/apt-pre-invoke-esm-service-status /var/lib/ubuntu-advantage/messages/apt-pre-invoke-no-packages-apps.tmpl;
        cp /var/lib/ubuntu-advantage/messages/apt-pre-invoke-esm-service-status /var/lib/ubuntu-advantage/messages/apt-pre-invoke-packages-apps;
        cp /var/lib/ubuntu-advantage/messages/apt-pre-invoke-esm-service-status /var/lib/ubuntu-advantage/messages/apt-pre-invoke-packages-apps.tmpl;
    fi;
    [ -f "/etc/profile.d/activate_psd_user.sh" ] && rm /etc/profile.d/activate_psd_user.sh;
    [ -f "/etc/profile.d/check_first_login.sh" ] && rm /etc/profile.d/check_first_login.sh;
    [ -f "/etc/profile.d/check_first_login_reboot.sh" ] && rm /etc/profile.d/check_first_login_reboot.sh;
    [ -f "/etc/profile.d/ssh-title.sh" ] && rm /etc/profile.d/ssh-title.sh;
    [ -f "/etc/update-motd.d/10-header" ] && rm /etc/update-motd.d/10-header;
    [ -f "/etc/update-motd.d/30-sysinfo" ] && rm /etc/update-motd.d/30-sysinfo;
    [ -f "/etc/update-motd.d/35-tips" ] && rm /etc/update-motd.d/35-tips;
    [ -f "/etc/update-motd.d/40-updates" ] && rm /etc/update-motd.d/40-updates;
    [ -f "/etc/update-motd.d/98-autoreboot-warn" ] && rm /etc/update-motd.d/98-autoreboot-warn;
    [ -f "/etc/update-motd.d/99-point-to-faq" ] && rm /etc/update-motd.d/99-point-to-faq;
    [ -f "/etc/update-motd.d/80-esm" ] && rm /etc/update-motd.d/80-esm;
    [ -f "/etc/update-motd.d/80-livepatch" ] && rm /etc/update-motd.d/80-livepatch;
    [ -f "/etc/apt/apt.conf.d/02compress-indexes" ] && rm /etc/apt/apt.conf.d/02compress-indexes;
    [ -f "/etc/apt/apt.conf.d/02periodic" ] && rm /etc/apt/apt.conf.d/02periodic;
    [ -f "/etc/apt/apt.conf.d/no-languages" ] && rm /etc/apt/apt.conf.d/no-languages;
    [ -f "/etc/init.d/armhwinfo" ] && rm /etc/init.d/armhwinfo;
    [ -f "/etc/logrotate.d/armhwinfo" ] && rm /etc/logrotate.d/armhwinfo;
    [ -f "/etc/init.d/firstrun" ] && rm /etc/init.d/firstrun;
    [ -f "/etc/init.d/resize2fs" ] && rm /etc/init.d/resize2fs;
    [ -f "/lib/systemd/system/firstrun-config.service" ] && rm /lib/systemd/system/firstrun-config.service;
    [ -f "/lib/systemd/system/firstrun.service" ] && rm /lib/systemd/system/firstrun.service;
    [ -f "/lib/systemd/system/resize2fs.service" ] && rm /lib/systemd/system/resize2fs.service;
    [ -f "/usr/lib/armbian/apt-updates" ] && rm /usr/lib/armbian/apt-updates;
    [ -f "/usr/lib/armbian/firstrun-config.sh" ] && rm /usr/lib/armbian/firstrun-config.sh;
    [ -d "/var/lib/lightdm" ] && ( chown -R lightdm:lightdm /var/lib/lightdm;
    chmod 0750 /var/lib/lightdm )
## end contents of 'board_side_bsp_cli_preinst'

set +x # Disable debugging
echo "Armbian 'armbian-bsp-cli-rk3128-box-current' for '1-PC8f91-V5e5d-He14c-B8122-Rf36a': 'preinst' finishing."
true
